[package]
name = "bevoids"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
rand = "0.8.4"
bevy = "0.5"
thiserror = "1.0"
derive_more = "0.99"

[patch.crates-io]
bevy = { git = "https://github.com/bevyengine/bevy" }
#bevy = { path = "../bevy" }

[profile.dev.package."*"]
opt-level = 3
