[package]
name = "bevoids_assets"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.6", default-features = false }
bevy-embasset = "0.4.1"
#bevy-embasset = { path = "../../bevy-embasset" }
paste = "1.0"
strum = { version = "0.23", features = ["derive"] }
