[package]
name = "bevoids"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy_asset_map = { path = "../bevy_asset_map" }
bevy_effects = { path = "../bevy_effects" }
bevy_egui = "0.7"
structopt = "0.3"
bevy_kira_audio = { version = "0.6.0", features = ["mp3", "wav"] }
parry2d = "0.7"
rand = "0.8.4"
derive_more = "0.99"
enum-iterator = "0.7"
walkdir = "2.3"
itertools = "0.10"
toml = "0.5"
serde = "1.0"
serde_derive = "1.0"
bevy-inspector-egui = { version = "0.6", optional = true }

[dependencies.bevy]
version = "0.5"
default-features = false
features = [
    #"bevy_dynamic_plugin",
    "render",
    "bevy_wgpu",
    "bevy_winit",
    #"bevy_gilrs",
    #"bevy_gltf",
    "png",
    "jpeg",
    "x11",
    #"wayland",
    #"trace",
    #"wgpu_trace",
]

[features]
inspector = ["bevy-inspector-egui"]
