[general]
animation_fps = 30
max_score = 100

[asteroid]
size_max = 150
size_min = 20
speed_max = 125
speed_min = 25
zpos_min = 100
zpos_max = 200
spawndelay_initial_seconds = 15
spawndelay_min_seconds = 5
spawndelay_multiplier = 0.98
spawn_player_distance = 200
split_number = 2
split_size_factor = 0.66

[window]
width = 800
height = 800

[player]
size = 50
zpos = 900
accelleration = 250
decelleration = 33.3
turn_speed_slow = 2.36
turn_speed_fast = 4.71
max_speed = 800
gun_ypos = 20
flame_width = 15
flame_ypos = -30

[laser]
size = 35
speed = 500
lifetime_miliseconds = 800
fadeout_miliseconds = 250

[volume]
laser = 0.6
thruster = 0.4
ship_explosion = 1.0
asteroid_explosion = 0.8
